### ISSUE TITLE
Timer Decorator

### ISSUE THREAD

**Issue by sageteam-org** [sageteamorg/django-sage-painless#6]
https://github.com/sageteam-org/django-sage-painless/blob/1e8632982edb6f465bdf191eb5f92ae9b379c122/sage_painless/services/admin_generator.py#L77

To have better practice convert `time.time` into a timer report decorator on your function

**Comment by mehran-rahmanzadeh** [comment]
We have to calculate duration and return it in function, It is not possible with decorators so it fixed by a service as a mixin class.
